sudo: required
services:
    - docker

before_install:
    - docker build -t dguarines/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run dguarines/react-test npm test -- --coverage

after_success:
    - docker build -t dguarines/multi-client ./client
    - docker build -t dguarines/multi-nginx ./nginx
    - docker build -t dguarines/multi-server ./server
    - docker build -t dguarines/multi-worker ./worker
    # Log in to the docker CLI
    
    # Take those images and push them to docker hub